---
- name: Elastic Installer
  gather_facts: true
  hosts: elastic
  become: True

  vars:
    es_version: '7.16.3'
    cluster_name: "{{ ansible_facts['nodename'] }}"
    es_heap_size: "512m"
    admin_password: "Woegh6"
    initial_master_nodes: "['{{cluster_name}}-1']"
    xpack_security_enabled: "true"
    xpack_security_transport_ssl_enabled: "true"
    xpack_security_transport_ssl_verification_mode: "certificate"
    xpack_security_transport_ssl_key: "nodes.key"
    xpack_security_transport_ssl_certificate: "nodes.crt"
    xpack_security_transport_ssl_certificate_authorities: "ca.crt"
    xpack_security_http_ssl_enabled: "true"
    xpack_security_http_ssl_verification_mode: "certificate"
    xpack_security_http_ssl_key: "client.key"
    xpack_security_http_ssl_certificate: "client.crt"
    xpack_security_http_ssl_certificate_authorities: "ca.crt"
    xpack_monitoring_enabled: 'false'
    xpack_monitoring_collection_enabled: 'false'

  tasks:
          
  - name: Installing Docker Service
    ansible.builtin.include_role:
      name: asbrl-docker
      apply:
        tags:
          - docker
    vars:
      asbrl_docker_install_docker: True
      asbrl_docker_install_certificates: False
      asbrl_docker_install_registry: False
      asbrl_docker_install_watchtower: False      
    tags:
      - docker


  - name: "ElasticSearch Docker Network"
    community.docker.docker_network:
      name: elasticsearch
      enable_ipv6: false
      driver: "bridge"
      ipam_driver: "default"
      ipam_config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
    tags:
      - elasticsearch

  - name: "Deploy ElasticSearch Node 1"
    ansible.builtin.include_role:
      name: asbrl-elasticsearch
      apply:
        tags:
          - elasticsearch      
    vars:
      build: "{{ es_version }}"
      container_name: "{{ cluster_name }}-1"
      hostname: "{{ cluster_name }}-1"
      discovery_service: "['{{cluster_name}}-2', '{{cluster_name}}-3']"
      docker_published_ports:
        - "9200:9200"
    tags:
      - elasticsearch

  - name: "Deploy ElasticSearch Node 2"
    ansible.builtin.include_role:
      name: asbrl-elasticsearch
      apply:
        tags:
          - elasticsearch      
    vars:
      build: "{{ es_version }}"
      container_name: "{{ cluster_name }}-2"
      hostname: "{{ cluster_name }}-2"
      discovery_service: "['{{cluster_name}}-1', '{{cluster_name}}-3']"
      docker_published_ports:
        - "9201:9200"
    tags:
      - elasticsearch

  - name: "Deploy ElasticSearch Node 3"
    ansible.builtin.include_role:
      name: asbrl-elasticsearch
      apply:
        tags:
          - elasticsearch      
    vars:
      build: "{{ es_version }}"
      container_name: "{{ cluster_name }}-3"
      hostname: "{{ cluster_name }}-3"
      discovery_service: "['{{cluster_name}}-1', '{{cluster_name}}-2']"
      docker_published_ports:
        - "9202:9200"
    tags:
      - elasticsearch
