---
- name: Elastic Installer
  gather_facts: true
  hosts: elastic
  become: True

  vars:
    es_version: '7.16.3'
    cluster_name: 'es6815a'

  tasks:
          
  - name: Installing Docker Service
    ansible.builtin.include_role:
      name: asbrl-docker
      apply:
        tags:
          - docker
    vars:
      asbrl_docker_install_docker: True
      asbrl_docker_install_certificates: False
      asbrl_docker_install_registry: False
      asbrl_docker_install_watchtower: False      
    tags:
      - docker

  - name: "Deploy ElasticSearch Node 1"
    ansible.builtin.include_role:
      name: asbrl-elasticsearch
      apply:
        tags:
          - elasticsearch      
    vars:
      build: "{{ es_version }}"
      container_name: "{{ cluster_name }}-1"
      hostname: "{{ cluster_name }}-1"
      initial_master_nodes: "['{{cluster_name}}-1']"
      es_heap_size: "256m"
      admin_password: "my_secret"
      docker_published_ports:
        - "9200:9200"
      xpack_security_enabled: 'true'
      xpack_monitoring_enabled: 'false'
      xpack_monitoring_collection_enabled: 'false'
    tags:
      - elasticsearch

  - name: "Deploy ElasticSearch Node 2"
    ansible.builtin.include_role:
      name: asbrl-elasticsearch
      apply:
        tags:
          - elasticsearch      
    vars:
      build: "{{ es_version }}"
      container_name: "{{ cluster_name }}-2"
      hostname: "{{ cluster_name }}-2"
      initial_master_nodes: "['{{cluster_name}}-1']"
      es_heap_size: "256m"
      admin_password: "my_secret"
      docker_published_ports:
        - "9201:9200"
      xpack_security_enabled: 'true'
      xpack_monitoring_enabled: 'false'
      xpack_monitoring_collection_enabled: 'false'
    tags:
      - elasticsearch

  - name: "Deploy ElasticSearch Node 3"
    ansible.builtin.include_role:
      name: asbrl-elasticsearch
      apply:
        tags:
          - elasticsearch      
    vars:
      build: "{{ es_version }}"
      container_name: "{{ cluster_name }}-3"
      hostname: "{{ cluster_name }}-3"
      initial_master_nodes: "['{{cluster_name}}-1']"
      es_heap_size: "256m"
      admin_password: "my_secret"
      docker_published_ports:
        - "9202:9200"
      xpack_security_enabled: 'true'
      xpack_monitoring_enabled: 'false'
      xpack_monitoring_collection_enabled: 'false'
    tags:
      - elasticsearch
