---
- name: MCLB Installer
  gather_facts: true
  hosts: mclb 
  become: True

  vars:
    docker_network_gw: '172.17.0.1'
    opster_assets_url: 'https://opster-rpms.s3.amazonaws.com/sgw'
    opster_mclb_grafana_dashboard: 'SGW-Grafana-Dashboard.json'
    opster_mclb_kibana_dashboard : 'kibana-dashboard-export.ndjson'

    es_version: '7.15.1'
    deploy_using: 'docker'  

  tasks:

          
  - name: Installing Docker Service
    ansible.builtin.include_role:
      name: asbrl-docker
      apply:
        tags:
          - docker
    vars:
      asbrl_docker_install_docker: True
      asbrl_docker_install_certificates: False
      asbrl_docker_install_registry: False
      asbrl_docker_install_watchtower: False      
    tags:
      - docker

  - name: Deploy Seach Gateway Service
    ansible.builtin.include_role:
      name: opster_search_gateway
      apply:
        tags:
          - sgw          
    vars:
      opster_mclb_errorHandling:
        kafka:
          bootstrapServers: "kafka:9092"
          groupId: "mclb"
          topic: "mclb-"

      opster_sgw_backends:
        - url: 'https://172.31.27.79:9200'
          default: 'true'
          username: 'elastic'
          password: 'Woegh6'
        - url: 'https://172.31.27.79:9201'
          default: 'false'
          username: 'elastic'
          password: 'Woegh6'
        - url: 'https://172.31.27.79:9202'
          default: 'false'
          username: 'elastic'
          password: 'Woegh6'
    tags:
      - sgw
