---
- name: MCLB Installer
  gather_facts: true
  hosts: mclb 
  become: True
  
  vars:
    network_name: mclb

  tasks:
          
  - name: Installing Docker Service
    ansible.builtin.include_role:
      name: asbrl-docker
      apply:
        tags:
          - docker
    vars:
      asbrl_docker_install_docker: True
      asbrl_docker_install_certificates: False
      asbrl_docker_install_registry: False
      asbrl_docker_install_watchtower: False      
    tags:
      - docker

  - name: ElasticSearch Docker Network
    community.docker.docker_network:
      name: "{{ network_name }}"
      enable_ipv6: false
      driver: bridge
      ipam_driver: default
      ipam_config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
    tags:
      - docker 

  
  - name: Installing Kafka Service
    ansible.builtin.include_role:
      name: asbrl_kafka
      apply:
        tags:
          - kafka
    vars:
      docker_network_name: "{{ network_name }}" 
    tags:
      - kafka

  - name: Deploy MCLB Service
    ansible.builtin.include_role:
      name: opster_mclb_role
      apply:
        tags:
          - mclb
    vars:
      deploy_using: 'docker'
      docker_network_name: "{{ network_name }}" 
      docker_published_ports:
        - "0.0.0.0:8200:8200"
        - "0.0.0.0:5555:5555"
      
      opster_mclb_errorHandling:
        kafka:
          bootstrapServers: "kafka:9092"
          groupId: "mclb"
          topic: "mclb-"

      opster_mclb_sslserverloader:
        type: 'files'
        certFileName: '/app/resources/certificates/client.crt'
        privateKeyFileName: '/app/resources/certificates/client.key'

      opster_mclb_backends:
        - url: 'https://172.31.13.209:9200'
          default: 'true'
          username: 'elastic'
          password: 'Woegh6'
        - url: 'https://172.31.13.209:9201'
          default: 'false'
          username: 'elastic'
          password: 'Woegh6'
        - url: 'https://172.31.13.209:9202'
          default: 'false'
          username: 'elastic'
          password: 'Woegh6'
        - url: 'https://172.31.13.209:9200'
          default: 'false'
          username: 'elastic'
          password: 'Woegh6'
        - url: 'https://172.31.13.209:9201'
          default: 'false'
          username: 'elastic'
          password: 'Woegh6'
        - url: 'https://172.31.13.209:9202'
          default: 'false'
          username: 'elastic'
          password: 'Woegh6'
    tags:
      - mclb
