all:
  hosts:
    node1:
      ansible_host: 192.168.254.3
      ansible_port: 22
      ansible_user: vagrant
      ansible_private_key_file: ~/.ssh/id_rsa
    node2:
      ansible_host: 192.168.254.4
      ansible_port: 22
      ansible_user: vagrant
      ansible_private_key_file: ~/.ssh/id_rsa