---
- name: Installing Prerequisites
  gather_facts: False
  hosts: localhost
  become: False

  tasks:

  - name: Galaxy Collections
    ansible.builtin.command: ansible-galaxy collection install -U -r requirements.yml
    tags:
      - pre

  - name: Galaxy Roles
    ansible.builtin.command: ansible-galaxy role install -f -r requirements.yml
    tags:
      - pre

- name: Include the Installer
  import_playbook: installer.yaml