- src: git+https://github.com/moegui/asbrl-docker.git
  version: 0.4.0
- src: git+https://github.com/moegui/asbrl-cadvisor.git
  version: 0.3.1
- src: git+http://github.com/moegui/asbrl-prometheus.git
  version: master
