---
roles:
- src: https://github.com/moegui/asbrl-docker.git
  version: 0.4.0
- src: https://github.com/moegui/asbrl-cadvisor.git
  version: 0.3.1
- src: http://github.com/moegui/asbrl-prometheus.git
  version: master

collections:
  - name: ansible.posix
  - name: community.docker