---
- name: Ansible 102
  hosts: all
  gather_facts: no

  tasks:

  - name: Upgrade Distribution
    apt:
      name:
        - nginx
      state: present
      upgrade: dist
      update_cache: true

  - name: Reboot Machines after Upgrade
    reboot:
---


